sudo: true
dist: trusty
services:
- docker
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -t spotim-devops-challenge .
    - docker images
    - docker tag spotim-devops-challenge $DOCKER_USERNAME/spotim-devops-challenge
    - docker push $DOCKER_USERNAME/spotim-devops-challenge
  - stage: test
    script: docker run --rm $DOCKER_USERNAME/spotim-devops-challenge curl 127.0.0.1:5000/health
env:
  global:
    DOCKER_USERNAME:
      secure: yzrRY+J0o7TQjpf2B//RVUe64lElRGF6M4gxjYrqeIsgyx8FKUpD6dba2vViywo10MWqKQrHYVdFZaz3YTPS7Zf0VCsi6Z051Aglo6eIfDQBC0vcZkUrAXZLS9R8kEub5HcbHlXkylrXFHmzeBdrRKYAJzJsCabsc8eFDjJf9NJu2j7a0tdlvswItI2cpeAv2LT+T9FxtkR2HWgyRW7knlNx7ZvjTaLvC7sWjvfCsZj6Oq3OFZzdcV+OO+swLeafg4YH7sqinB2h3TyQticlVCK0gNSGEcI/XGIAhR05Ix7JzHPM3duGqMvmbUbQknIkdu9Ejr9ucKXgWoMWbD5RJ7XUya8Pd1vX1WkHoasHXRxYmem+9tfImQSzb0t7rSAN2HQjUkHN51d3++N2mgJuT0aS8YJRywDxFmOg2jJUXttcLjsD7qCa9qrmA9rgPIzzXcKDBE+qT7mNzqy6PxY58QBqfaVSb1Vxg97t4tlVjzreYf+8/r7dF94mfRSwSFuRC7OGZWoL6Zlaxb/mCrg9NeDr3aNv/A7PoBzjOnWKPwLdXy5FvJ1ti8XTs4522W5+e6SYuV5iMaedWXEQiRQm1oEEiipgU3th6GazrSVrs5rCKyMH3hQoLIe0yprMnfzX6dHvQbd4tsdXez999hL1rItiQLyzesgv2cxxOvv9ngA=
    DOCKER_PASSWORD:
      secure: AjLrzbCFIEDVcpMu6+65bAwgl3Ce6DWJJHsHvhg3yXmw8/AdpEld0XpZ/xTrWXn01oYWouuvLQ5E/ziBw5ChrEekiGaO/0Lp7Kl1RjLwudix9lSthQivUgOJ//VYcAR2qk0WAdcghW4FUH+AYI2DqKTuHJQV3fscTPiP3nu5jktgf2XLclphb5BwEQqMJmXW4KLEd6GmThVXxU2WR1MisdYqF6N2IHYf6dowZ3sovdn0Hfqfs0hGfZftNJiEDXfbDQXxr7uP5cY3+jLgc9l3kvl3srl6Lux+ItcD7yFhzQ6iRenQKF4ezfzAajMw5DKQJ/6KxMCJLGwMpCtvWBgzv2UjH0/Vq6cCoiyUiRYrWfRt8RRJO3+0/ojhuokJ2yWBCZcKmv+jWqyXQhFdds3EvjX+M3cRXiMhaB+HpC+AqUUx7z6Q+wpojwRz7q4Ik+epMuK+wyi1IAZdd1JHNzk4ibYY/g2j3YNfTmJW0WHFzE/U00BEmRkp58o1HmFkCS7hF+nc/cwgP8RxUYU3wk1kr5D7OwGhVpK9DfrMVBbTWWI3tJyyj0Eyo+iToF0xJRk8YhEaF0Emo9ZpjAyOZkNaIM3ILVPgMH61Zs21q5CfBZckBp2sCEj/HMXVUojZ6ZH5XuY1GkWceqXrMhr+6vwJKDou0gzcaRuueEnla+hUpM0=