sudo: true
dist: trusty
services:
- docker
env:
  global:
  - secure: D1FOCMcP287GZLXIEn3xxLzBNKIvrMEeUwhevnlOQWkogGMZw/eJlZZX7UpRpJ9M2Qnf4daSkfKcQV9OsushT+4Hlz4l0yMWHgXU0BhC6ExqOt2QDlnOPOojQUUm4L0ha6bBOgtkFXPesFM4R0nALcrBRhYg0ORhLTUc4pQTXhmzz9rd3FWWR6xSDII42zJFkY6UMWwgt1rBkRSZw+jwtOpPagx3b4y7fIVy/k8AHPRX91WQaldL4rXzigMigUvdN6hyjQhhIyYoJpMs1XtnF595aC6s9OcZq9U0QT0RuxU2KrNxq1/FA0Yhm4SzktyvDSeA+eG8TKjmTAERwYFV5lLN33D7nF7AYdqqaBxffndh1/TrJVL4CSm4oHKZJoZVwyLehwzQQtJTVMDayVFKKOxttco6jkzBKgWlZZ0qGXMwsKKZ30SmZXpHhFeeeMJsB7fyVvclAcYhFhrb/OTxDYPTSI6V+iV5LVJbJSmDvCNwcEIesxZbHKutB7gNTQ+kITjrx34QsNdsucuX9aHw5JLkY3zSnY9C4uMG2maxJiSjMTSmpZSJMsDT1mHDoN+wPUtWpSyZSHM4oOUYztgCL2nu0J/OKpLPwkVbJdMS5ZmSodzJQqnXnKCM65eq/uGNiTpxr637EQYkLvCLFdlavy/INPMrvIF0D1kHHGe7rMw=
  - secure: SwiRhrJq6vwCQRbAU/xFgpQURiRxoTlyjup6a5yMIX2x0GTvERz6gre4VTJfUf7rkfFIrbj7SO955pAnUrZob+f3hAvYkXCM+9X56O9unocJUPKnmgH5tpBIO/gvUiONcsU8Vqfx5aYqRT93mW3wCpq3eqDdD5NrDlZEafasQc7z8+lrJc1iNBSlqCeRf1wPibFX7tVmPEMkI5k0GpfJxULISzjh4Ge3TZi4rqnKexu+CrAO+O4xRy5U8TjLaSxBZdeZvyqSxZycGpnsVfgxNoIFrAFivJuj2dLnbyoeIwgVGc1RVKvGNhKFKMyHMiTHCZOv/x1VM48fNRGYD6BkDkgSH1Bcy8GBEdrDR4oGPX+P1eR4VcIT2gY03v4w/XxvNJxWdWFAeCyDl+Rhja7GRqOmgp3jEEJLChcjcN+9D4FuEgYl8z7Bpx6G53EncZ2qSATz4YxYwwq82CHEF1wZzS9W+PR/J9XeySL3SyGj0u3MvaHZAaLGvwmzpNVXtbC8jDgJ20eIByudpG2m7fVeEbiaBYGTKqp626NUZSphMNIjnnjnlRH+K/1DQkx9dHJE37ku0ZURbtLPeJNkLZFrCnPDtyM4Dtm7oZrXbQ9Zuqka9qFuJFesVXvxD3CBQwf+nhcpdOA9j1UZtVW5futomwsJrO7DeKD9y25B/bjFOto=
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
    - docker build -t spotim-devops-challenge .
    - docker images
    - docker tag spotim-devops-challenge $DOCKER_USERNAME/spotim-devops-challenge
    - docker push $DOCKER_USERNAME/spotim-devops-challenge
  - stage: test
    script: docker run --rm $DOCKER_USERNAME/spotim-devops-challenge curl 127.0.0.1:5000/health
