sudo: true
dist: trusty
services:
- docker
jobs:
  include:
  - stage: build docker image
    script:
    - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
    - docker build -t spotim-devops-challenge .
    - docker images
    - docker tag spotim-devops-challenge ${DOCKER_USERNAME}/spotim-devops-challenge
    - docker push ${DOCKER_USERNAME}/spotim-devops-challenge
  - stage: test
    script: docker run --rm ${DOCKER_USERNAME}/spotim-devops-challenge curl 127.0.0.1:5000/health
env:
  global:
  - secure: 1JkzD6eQp2QHIlleySDdHS+YlHdjZvrR0ilhTrp/e2th+oEeb9m5dNSPeBtOKZGsghZDwwn+Pc77IyxOJaXM7W9e3iS66N1TKTVIWiXBbU4CwkWEt5IOcLwTyXyYL+5ArsZYeuSooH2dnp1ywVQ1pEKTXtqkGJLOkcMlpPvz38gbTfhjvs+0xloCqnRjrYV7aKx0HYwDvPtfKCWQTcD4rGnzZ+UME+5pkjaHJi3HpTXoZUuYh0FfxrvgfJtF+3TqlcfQNMV67DqEIrQ/IApz/fhgvuVKJHSx9zjli9DNrDTVa+aY6qXja19E99fwQ/+mwFqjbC7AHW+ZLdUVvZWa76iRDMO1Ke5+6w4GOBRa3Ikb9YGrST4mSSjWlwRTTDc7V1f4CFywk6XqLGwoMOOdEAX8m6Dh/kmXV4knMXOW3oL5hhiv2oACPzQngYmaiJ3l3rlcCQNVTqkKF6F1E1Vbu5J/u+zRHOG5OHW24PV16fzL84S2TuXh3CX8V+52sv02V5zJyV/4XjJ0Lv/AnNxhbETdzQjNua+VghNG8OsXnWoWsPYOJQdQ25yHfHk8v3aXmUbLURW48LhLxatzl6IdNn+FwM61E4TjO0vaVkXxIbM6XGk4kvh2tGin/qAHN+Uaw+HXYA4CB0nhXTnPPFHGpZWll2d5YaTEJViD3LPOeNo=
  - secure: Z7hTq8ixpyF1KCbOdzeBYr+/g9fvgpCBCBqlw2TMulm/fvVFdpstXR2t96Z/hISOqVrGGBj69fr5/eErswSqYQ5aO6zEfMzP+xZQEtE1uXQ9WO1ASGpW0lXJrlcaCfDUyNEcr/eZ9agHo0s7RYR+cxo4Zlut1/IjgMe8b0SICqcKWLlj+gWvVfTtccyfuvyAm91NC7uRA6T+vmh75f55M6oykJk5HFQKyijD1bNVH6huMgx6bgFd1lDXMgy1B19OsGCUWlCjqfh+/K3Vvp9glZSZMD6V5Wv2zmoWMNN854vesr+rYpUJR+fwE2CTgmum4qjBBtTRz6L8n2cjgOw+2lxwXawRzKZnMEyFKU4h9wrp8MTVYANTjI1Ey5cRq7fXam9Dcr9jHgHfx1XlaRj7s/VlcW7d7T6OHzh/fGNVQk28Wmg9pNpA9lknOHa60tg8wiL6/ipMMeyM7ldjEHFvU4OUqhTzmB68oSXaoNyGdokPMJcDtLlzDqaH9zAL1+1SY9I4getXeI8n2QIRmxb31fVCvMWs14tcx4athUK6ScFrfNnwqfoJSB7/wl47H5YWbsszb7Nx37AmlZeVz0/9jp00RE4RIA35GS+KdVMrS7saP6q8IHlDfwfAtW8jKt2AXdg6ET2ZHKgUA1xZHUoTgj/yinB5SqsHwgBfN/T+5GY=
